### ISSUE TITLE
Consider enabling `add(path)` to the files API

### ISSUE THREAD

**Issue by daviddias** [ipfs/interface-js-ipfs-core#118]
@jbenet brought up that a lot of users will expect `ipfs.add(path)` to just work as if they were in the terminal. 

In the past, we went through several iterations and discussions and eventually ended up agreeing that it would be beneficial to have utilities like [addFromFs and addFromUrl](https://github.com/ipfs/js-ipfs-api#add-files-or-entire-directories-from-the-filesystem-to-ipfs) as actions that are explicit, this keeps the promise intact that code can be run in the browser and in Node.js, as long as the dev is using the ipfs-core API. 

We can add this feature, we will just need to be verbose about that caveat.

**Comment by dignifiedquire** [comment]
👎 on this, it makes the api more complicated, and having an api call that has entirely different semantics depending on if it is run in node.js or the browser seems like it will only cause more confusion.

**Comment by jbenet** [comment]
This is a basic expectation of ipfs nodes and tooling.

- I would expect `ipfs.add(path)` to work, everywhere, and only fail when the path is inaccessible.
- in the browser, the limitation is the access to the files, similar to how in the filesystem permissions may hide parts of the fs. `ipfs.add("~/foo/bar")` is not possible in the browser because the files are not accessible.
- you could choose to make `ipfs.add(url)` work in the browser, as i would expect to work. (http is sort of the fs of the web.)

Bottom line, these should be trivially easy to use:

```js
// direct analogues with ipfs add in the cli, in node.
ipfs.add("~/path/to/my-file")
ipfs.add("~/path/to/my-dir", {recursive: true})
ipfs.add("my-file")
ipfs.add("my-dir", {recursive: true})
ipfs.add(stream) // makes a file

// direct analogues with ipfs add in the cli, but on the browser
ipfs.add("https://foo.com/my-page")
// arguably, people would expcet this to work like wget mirroring:
// ipfs.add("https://foo.com/my-page", {recursive: true})
// but i'm fine not supporting it.
```

Conversely, i would expect cat to work equally easily:

```js
ipfs.cat(ipfsPath) # returns a stream
```

### The emphasis here is in:

- consistency with ipfs tooling + expectations everywhere else
- trivially simple command for trivially simple use case
- maintaining backwards compatibility. [don't break interfaces.](https://felipec.wordpress.com/2013/10/07/the-linux-way/)

**Comment by jbenet** [comment]
"i just want to add some json and get it back" this should be absolutely trivial, and exactly the same as it works in the cli.

**Comment by hacdias** [comment]
@diasdavid it seems to be already working on the [JavaScript API](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#javascript---ipfsfilesadddata-options-callback). Is there anything else to do on this issue I can help with?

**Comment by wraithgar** [comment]
The docs in the JavaScript API were erroneous. The files.add method only allows Buffers or Streams (either directly or as the `content` attribute in an object)

**Comment by diasdavid** [comment]
There is a very valuable and impressive work being done and thought through by @alanshaw, @olizilla and @achingbrain with regards to APIs around Files and js-ipfs APIs in general (ipfsx).

As a stepping stone towards that, I want to bring the .addFromFs to the top level. In the future there will be just on ipfs.add command when we have the async generators goodness (and no more myriad of Streams)

**Comment by achingbrain** [comment]
Adding files by path has been split out into the [`globSource`](https://github.com/ipfs/js-ipfs/blob/447b44d1b64714f5ed0cafba166ad0a4dbbb587c/packages/ipfs-utils/src/files/glob-source.js) module - please open an issue on ipfs/js-ipfs if there's any further work to be done here.
